apiVersion: v1
kind: Service
metadata:
  name: open-telemetry-app
  labels:
    app: open-telemetry-app
spec:
  selector:
    app: open-telemetry-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
